export const fishData = [
 {
  name: "Cod",
  image: "/Fish/Cod.png",
  grey_image: "/Fish/Cod_grey.png",
  fish_value: 1,
  facts: "I am Cod",
 },
 {
  name: "Darth Fisher",
  facts: "Luke, I am your father",
  image: "/Fish/Darth Fisher.png",
  grey_image: "/Fish/Darth Fisher_grey.png",
  fish_value: 5,
 },
 {
  name: "Dory",
  fish_value: 10,
  grey_image: "/Fish/Dory_grey.png",
  facts: "I forget what I was going to say...",
  image: "/Fish/Dory.png",
 },
 {
  name: "Eleventicles",
  grey_image: "/Fish/Eleventicles_grey.png",
  fish_value: 15,
  image: "/Fish/Eleventicles.png",
  facts: "you gotta be squiddin me",
 },
 {
  name: "Flat Boi",
  fish_value: 12,
  facts: "stacking flat stacks",
  image: "/Fish/Flat Boi.png",
  grey_image: "/Fish/Flat Boi_grey.png",
 },
 {
  name: "Jaws",
  fish_value: 50,
  image: "/Fish/Jaws.png",
  facts: "He's old now so you don't see him knocking about much",
  grey_image: "/Fish/Jaws_grey.png",
 },
 {
  name: "McFish",
  facts: "Bringing many happy memories to fast food goers across the world",
  grey_image: "/Fish/McFish_grey.png",
  image: "/Fish/McFish.png",
  fish_value: 20,
 },
 {
  name: "Red Rum",
  fish_value: 3,
  image: "/Fish/Red Rum.png",
  grey_image: "/Fish/Red Rum_grey.png",
  facts: "fastest fishy around",
 },
 {
  name: "chomp",
  grey_image: "/Fish/chomp_grey.png",
  image: "/Fish/chomp.png",
  fish_value: 100,
  facts: "a chomp but certainly not a chump",
 },
 {
  name: "coolfish",
  facts: "the coolest of all the fish",
  fish_value: 15,
  image: "/Fish/coolfish.png",
  grey_image: "/Fish/coolfish_grey.png",
 },
 {
  name: "dumbo",
  facts: "not as dumbo as he looks",
  fish_value: 75,
  image: "/Fish/dumbo.png",
  grey_image: "/Fish/dumbo_grey.png",
 },
 {
  name: "kaboom",
  grey_image: "/Fish/kaboom_grey.png",
  facts: "this fish is the bomb",
  image: "/Fish/kaboom.png",
  fish_value: 250,
 },
 {
  name: "magic fish",
  grey_image: "/Fish/magic fish_grey.png",
  facts: "the most magical fish in the sea ",
  image: "/Fish/magic fish.png",
  fish_value: 15,
 },
 {
  name: "northern fish",
  facts: "ee by gum, I love myself a Yorkshire Pud",
  grey_image: "/Fish/northern fish_grey.png",
  fish_value: 20,
  image: "/Fish/northern fish.png",
 },
 {
  name: "really big fish",
  grey_image: "/Fish/really big fish_grey.png",
  image: "/Fish/really big fish.png",
  fish_value: 100,
  facts: "this fish is the size of London",
 },
 {
  name: "tang fish",
  fish_value: 500,
  facts: "this fish is tangtastic",
  grey_image: "/Fish/tang fish_grey.png",
  image: "/Fish/tang fish.png",
 },
 {
  name: "the fish named Jordan",
  image: "/Fish/the fish named jordan.png",
  fish_value: 50,
  facts: "this fish likes to make games in its spare time",
  grey_image: "/Fish/the fish named jordan_grey.png",
 },
 {
  name: "zebra",
  image: "/Fish/zebra.png",
  facts: "evolving back into the sea",
  grey_image: "/Fish/zebra_grey.png",
  fish_value: 60,
 },
];
