export {default as background} from "../../assets/Background/background3.png";
export {default as boat} from "../../assets/Scenary/boat-360x117.png";
export {default as Cod} from "../../assets/Fish/Cod.png";
export {default as darthFisher} from "../../assets/Fish/Darth Fisher.png";
export {default as Dory} from "../../assets/Fish/Dory.png";
export {default as Jaws} from "../../assets/Fish/Jaws.png";
export {default as McFish} from "../../assets/Fish/McFish.png";
export {default as coolfish} from  "../../assets/Fish/coolfish.png";
export {default as magicFish} from "../../assets/Fish/magic fish.png";
export {default as northernFish} from "../../assets/Fish/northern fish.png";
export {default as reallyBigFish} from  "../../assets/Fish/really big fish.png";
export {default as theFishNamedJordan} from "../../assets/Fish/the fish named jordan.png";
export {default as character} from "../../assets/Character/character.png"; 
export {default as swimming} from "../../assets/Character/Swimming.png";
export {default as swimmingHorizontal} from "../../assets/Character/Swimming-Horizontal.png";
export {default as xlrock2flat} from "../../assets/Scenary/xlrock2flat.png";
export {default as xlrock2left} from "../../assets/Scenary/xlrock2left.png";
export {default as xlrock2right} from "../../assets/Scenary/xlrock2right.png";
export {default as xlrock1flat} from "../../assets/Scenary/xlrock1flat.png";
export {default as xlrock1left} from "../../assets/Scenary/xlrock1left.png";
export {default as xlrock1right} from "../../assets/Scenary/xlrock1right.png";
export {default as medrock1flat} from "../../assets/Scenary/medrock1flat.png";
export {default as smallrock1flat} from "../../assets/Scenary/smallrock1flat.png";
export {default as EventsCenter} from "../EventsCenter";

